---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: nexus.cjoop.top:18443/library/openjdk
    tag: 8-jdk
inputs:
- name: cities-repo
outputs:
- name: cities-service-build
run:
  path: bash
  args:
  - cities-repo/ci/tasks/build.sh

caches:
- path: gradle
- path: maven

params:
  PROJECT_TYPE: 