---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: nexus.cjoop.top:1443/openjdk
    tag: 8-jdk
inputs:
- name: repo
outputs:
- name: cities-service-build
run:
  path: /bin/bash
  args:
  - repo/ci/tasks/build.sh

caches:
- path: gradle
- path: maven

params:
  PROJECT_TYPE: 