---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: nexus.cjoop.top:18443/library/openjdk
    tag: 8-jdk
inputs:
- name: repo
- name: out
run:
  path: /bin/bash
  args:
  - repo/ci/tasks/show.sh