---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://gitee.com/cloud-native-java/concourse-tutorial.git
    branch: develop

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: resource-tutorial
  - task: create-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: "nexus.cjoop.top:18443/library/busybox"}

      inputs:
      - name: resource-tutorial
      outputs:
      - name: some-files

      run:
        path: resource-tutorial/tutorials/basic/task-outputs-to-inputs/create_some_files.sh

  - task: show-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: "nexus.cjoop.top:18443/library/busybox"}

      inputs:
      - name: resource-tutorial
      - name: some-files

      run:
        path: resource-tutorial/tutorials/basic/task-outputs-to-inputs/show_files.sh

