---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))

- name: cf-test
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: user
    password: pass
    organization: pcfdev-org
    space: test
    skip_cert_check: true

jobs:
- name: run-acceptance-tests
  plan:
  - get: repo
  - task: run-unit
    file: repo/ci/tasks/build.yml
    params:
      PROJECT_TYPE: ((project-type))
  - put: cf-test
    params:
      manifest: repo/cities-service/manifest-test.yml
      environment_variables:
        path: repo/cities-service/build/libs/cities-service-1.5.14-SNAPSHOT.jar
  - task: run-acceptance-tests
    file: repo/ci/tasks/acceptance-tests.yml
    params:
        CITY_SERVICE_URI: http://cities-test.local.pcfdev.io
        CITY_SERVICE_PORT: 80