---
resources:
- name: cities-repo
  type: git
  source:
    uri: https://gitee.com/cloud-native-java/spring-boot-cities.git
    branch: master

jobs:
- name: run-acceptance-tests
  public: true
  plan:
  - get: cities-repo
  - task: run-unit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: nexus.cjoop.top:1443/openjdk
          tag: 8-jdk
      inputs:
      - name: cities-repo
      outputs:
      - name: cities-service-build
      run:
        path: bash
        args:
        - -c
        - |
          export TERM=${TERM:-dumb}
          cd cities-repo/cities-service
          ./gradlew build
          cp build/libs/cities-service.jar ../../cities-service-build/

  - task: resource-cf-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: nexus.cjoop.top:1443/cf-cli-resource
          tag: latest
      inputs:
      - name: cities-service-build
      - name: cities-repo
      run:
        path: bash
        args:
        - -c
        - |
          ls cities-repo/cities-service/
          ls cities-service-build
          mkdir -p cities-repo/cities-service/build/libs/
          cp cities-service-build/cities-service.jar cities-repo/cities-service/build/libs/
          cf login -a https://api.local.pcfdev.io --skip-ssl-validation -u admin -p admin -o pcfdev-org -s test
          cd cities-repo/cities-service
          cf push -f manifest-test.yml -n cities-test