---
resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nexus.cjoop.top:1443/cf-cli-resource
    tag: latest

resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))

- name: cf-test
  type: cf-cli-resource
  source:
    api: https://api.local.pcfdev.io
    username: user
    password: pass
    org: pcfdev-org
    space: test
    skip_cert_check: true

jobs:
- name: run-acceptance-tests
  plan:
  - get: repo
  - task: run-unit
    file: repo/ci/tasks/build.yml
  - put: cf-test
    resource: cf-test
    params:
      command: push
      f: repo/cities-service/manifest-test.yml
  - task: run-acceptance-tests
    file: repo/ci/tasks/acceptance-tests.yml
    params:
        CITY_SERVICE_URI: http://cities-test.local.pcfdev.io
        CITY_SERVICE_PORT: 80