---
resources:
- name: resource-cities
  type: git
  source:
    uri: https://gitee.com/cloud-native-java/spring-boot-cities.git
    branch: master

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: resource-cities
  - task: create-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: "nexus.cjoop.top:1443/busybox"}

      inputs:
      - name: resource-cities
      outputs:
      - name: some-files

      run:
        path: resource-cities/ci/task-outputs-to-inputs/create_some_files.sh

  - task: show-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: "nexus.cjoop.top:1443/busybox"}

      inputs:
      - name: resource-tutorial
      - name: some-files

      run:
        path: resource-cities/ci/task-outputs-to-inputs/show_files.sh