---
resources:
- name: cities-repo
  type: git
  source:
    uri: https://gitee.com/cloud-native-java/spring-boot-cities.git
    branch: master

- name: resource-cf-test
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: test
    skip_cert_check: true

jobs:
- name: run-acceptance-tests
  public: true
  plan:
  - get: cities-repo
  - task: run-unit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: nexus.cjoop.top:1443/openjdk
          tag: 8-jdk

      inputs:
      - name: cities-repo
      outputs:
      - name: cities-service-build

      run:
        path: bash
        args:
        - -c
        - |
          export TERM=${TERM:-dumb}
          cd cities-repo/cities-service
          ./gradlew build

  - task: run-acceptance-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: nexus.cjoop.top:1443/openjdk
          tag: 8-jdk

      inputs:
      - name: cities-repo

      run:
        path: bash
        args:
        - -c
        - |
          ls cities-repo/cities-service/build/libs/