---
resources:
- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))

jobs:
- name: run-acceptance-tests
  plan:
  - get: repo
  - task: run-unit
    file: repo/ci/tasks/build.yml
  - task: show-files
    file: repo/ci/tasks/show.yml