---
resources:
- name: cities-repo
  type: git
  source:
    uri: https://gitee.com/cloud-native-java/spring-boot-cities.git
    branch: master
- name: resource-cf-test
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: test
    skip_cert_check: true

jobs:
- name: run-acceptance-tests
  public: true
  plan:
  - get: cities-repo
  - task: run-unit
    file: cities-repo/ci/tasks/build.yml
  - put: resource-cf-test
    params:
      manifest: cities-service-build/manifest-test.yml
  - task: run-acceptance-tests
    file: cities-repo/ci/tasks/acceptance-tests.yml
    params:
      CITY_SERVICE_URI: http://cities-test.local.pcfdev.io