---
resources:
- name: cities-repo
  type: git
  source:
    uri: https://github.com/cjjava/spring-boot-cities.git
    branch: master

- name: release-time
  type: time
  source:
    days:
    - Tuesday
    start: 21:20 +0800
    stop: 22:20 +0800
- name: cities-release
  type: github-release
  source:
    user: cjjava
    repository: spring-boot-cities
    access_token:

- name: resource-cf-test
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: test
    skip_cert_check: true

- name: resource-cf-staging
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: staging
    skip_cert_check: true

- name: resource-cf-prod
  type: cf
  source:
    api: https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: prod
    skip_cert_check: true

jobs:
- name: run-unit-test
  plan:
  - get: cities-repo
    trigger: false
  - task: run-unit
    file: cities-repo/ci/tasks/build.yml

- name: run-acceptance-tests
  plan:
  - get: cities-repo
    trigger: false
    passed: [run-unit-test]
  - task: run-unit
    file: cities-repo/ci/tasks/build.yml
  - put: resource-cf-test
    params:
      manifest: cities-service-build/manifest-test.yml
  - task: run-acceptance-tests
    file: cities-repo/ci/tasks/acceptance-tests.yml
    params:
      CITY_SERVICE_URI: http://cities-test.local.pcfdev.io

- name: publish-release
  plan:
  - get: cities-repo
    passed: [run-acceptance-tests]
  - get: release-time
    trigger: false
  - task: run-unit
    file: cities-repo/ci/tasks/build.yml
  - put: cities-release
    params:
      name: cities-repo/cities-service/release/name.txt
      tag: cities-repo/cities-service/release/tag.txt
      globs:
      - cities-service-build/build/libs/cities-service.jar

- name: deploy-to-staging
  plan:
  - aggregate:
    - get: cities-repo
      passed: [run-unit-test]
    - get: cities-release
      trigger: false
      passed: [publish-release]
  - put: resource-cf-staging
    params:
      manifest: cities-repo/cities-service/manifest-staging.yml
      path: cities-release/cities-service.jar
  - task: run-acceptance-tests
    file: cities-repo/ci/tasks/acceptance-tests.yml
    params:
      CITY_SERVICE_URI: http://cities-staging.local.pcfdev.io

- name: deploy-to-prod
  plan:
  - aggregate:
    - get: cities-repo
      passed: [deploy-to-staging]
    - get: cities-release
      trigger: false
      passed: [deploy-to-staging]
  - put: resource-cf-prod
    params:
      manifest: cities-repo/cities-service/manifest.yml
      current_app_name: cities-service
      path: cities-release/cities-service.jar